import type { Category, ObjectDef } from './types'

// Palette of placeable objects. All dimensions in meters; editable per-instance after placement.
export const CATALOG: ObjectDef[] = [
  { id: 'door_main', label: 'Main Entrance', category: 'door', w: 2.0, d: 0.3, h: 2.4, color: '#f59e0b', rule: 'edge' },
  { id: 'door_fire', label: 'Fire Exit', category: 'door', w: 1.5, d: 0.3, h: 2.4, color: '#ef4444', rule: 'edge' },
  { id: 'door_room', label: 'Room Door', category: 'door', w: 0.9, d: 0.15, h: 2.1, color: '#c9a06c', rule: 'floor' },
  // interior glass door: pairs with partitions and room walls
  { id: 'door_glass', label: 'Glass Door (interior)', category: 'door', w: 1.8, d: 0.15, h: 2.2, color: '#2f3237', rule: 'floor' },
  { id: 'parking', label: 'Parking (1 car)', category: 'parking', w: 5.0, d: 2.5, h: 0.05, color: '#8ea0b5', rule: 'outdoor' },
  { id: 'reception', label: 'Reception Counter', category: 'reception', w: 3.0, d: 1.5, h: 1.1, color: '#d9995f', rule: 'floor' },
  { id: 'storage', label: 'Storage Room', category: 'room', w: 4.0, d: 3.0, h: 2.6, color: '#b9b2a6', rule: 'floor' },
  { id: 'shoes', label: 'Shoe Rack', category: 'fixture', w: 2.0, d: 1.0, h: 1.6, color: '#b59b7c', rule: 'floor' },
  // access-control speed gate with face-recognition scanners (2 lanes at 2.4 m)
  { id: 'gate_face', label: 'Face-Scan Entry Gate', category: 'fixture', w: 2.4, d: 0.4, h: 1.1, color: '#c9ced4', rule: 'floor' },
  { id: 'toilet', label: 'Restrooms', category: 'room', w: 4.0, d: 3.0, h: 2.6, color: '#7dd3fc', rule: 'floor' },
  { id: 'cowork', label: 'Co-working Space', category: 'zone', w: 6.0, d: 5.0, h: 0.1, color: '#86efac', rule: 'floor' },
  { id: 'boulder', label: 'Boulder Wall (4.5 m)', category: 'wall_low', w: 15.0, d: 2.5, h: 4.5, color: '#60a5fa', rule: 'floor' },
  { id: 'lead', label: 'Lead Wall (12 m)', category: 'wall_high', w: 8.0, d: 2.5, h: 12.0, color: '#3b82f6', rule: 'floor' },
  { id: 'island', label: 'Island Boulder', category: 'wall_island', w: 6.0, d: 4.0, h: 4.0, color: '#818cf8', rule: 'floor' },
  { id: 'mats', label: 'Landing Mats', category: 'mat', w: 15.0, d: 4.0, h: 0.3, color: '#5b8ee6', rule: 'floor' },
  { id: 'mezzanine', label: 'Mezzanine Floor', category: 'mezzanine', w: 10.0, d: 6.0, h: 4.5, color: '#dcbd90', rule: 'floor' },
  { id: 'stairs', label: 'Staircase', category: 'stairs', w: 2.0, d: 5.0, h: 4.5, color: '#b0a695', rule: 'floor' },
  { id: 'column', label: 'Column', category: 'column', w: 0.4, d: 0.4, h: 4.5, color: '#9aa2ad', rule: 'floor' },
  { id: 'partition', label: 'Wall Partition', category: 'partition', w: 3.0, d: 0.15, h: 2.6, color: '#eae6dd', rule: 'floor' },
  // open steel railing for separating interior areas without blocking sight lines
  { id: 'rail', label: 'Steel Railing (1 m)', category: 'partition', w: 3.0, d: 0.08, h: 1.0, color: '#3e434a', rule: 'floor' },
  { id: 'person', label: 'Person', category: 'person', w: 0.5, d: 0.4, h: 1.7, color: '#3b82f6', rule: 'floor' },
  { id: 'training', label: 'Training Area', category: 'zone', w: 8.0, d: 6.0, h: 0.1, color: '#fca5a5', rule: 'floor' },
  { id: 'hyrox', label: 'Hyrox Zone', category: 'zone', w: 20.0, d: 15.0, h: 0.1, color: '#33363b', rule: 'floor' },
  { id: 'icebath', label: 'Ice Bath', category: 'fixture', w: 3.0, d: 2.0, h: 1.0, color: '#38bdf8', rule: 'floor' },
  { id: 'sauna', label: 'Sauna', category: 'room', w: 3.0, d: 3.0, h: 2.4, color: '#d4a373', rule: 'floor' },
  // tennis simulator: dark booth with the impact screen filling one 5 m end
  { id: 'tennis_sim', label: 'Tennis Simulator Room', category: 'room', w: 10.0, d: 5.0, h: 3.2, color: '#31445c', rule: 'floor' },
  { id: 'table', label: 'Table', category: 'furniture', w: 1.6, d: 0.8, h: 0.75, color: '#b98a5a', rule: 'floor' },
  { id: 'stool', label: 'Stool', category: 'furniture', w: 0.5, d: 0.5, h: 0.45, color: '#8a6f52', rule: 'floor' },
  { id: 'bench', label: 'Long Bench', category: 'furniture', w: 2.5, d: 0.4, h: 0.45, color: '#a1785c', rule: 'floor' },
  // ceiling: H = mounting height of the panel underside — match it to wall tops
  { id: 'ceiling', label: 'Ceiling Panel (H = mount height)', category: 'ceiling', w: 6.0, d: 6.0, h: 3.0, color: '#f4f1e8', rule: 'floor' },
  // vertical ceiling: hangs down from the roof like a partition; H = bottom edge height
  { id: 'bulkhead', label: 'Vertical Ceiling (H = bottom edge)', category: 'ceiling', w: 6.0, d: 0.15, h: 3.0, color: '#f4f1e8', rule: 'floor' },
  // hvac: for suspended items H = mounting height, adjusted with the green arrow
  { id: 'duct', label: 'Air Duct Run (H = mount height)', category: 'hvac', w: 6.0, d: 0.6, h: 3.6, color: '#b8bcc2', rule: 'floor' },
  { id: 'fcu', label: 'Cooling Coil / FCU (H = mount height)', category: 'hvac', w: 1.4, d: 0.45, h: 2.6, color: '#eef0f2', rule: 'floor' },
  { id: 'condenser', label: 'Condenser (hot coil)', category: 'hvac', w: 1.0, d: 0.42, h: 0.85, color: '#d8dadd', rule: 'outdoor' },
  { id: 'bigfan', label: 'HVLS Big Fan (H = mount height)', category: 'hvac', w: 4.0, d: 4.0, h: 5.5, color: '#6b7280', rule: 'floor' },
  { id: 'floorfan', label: 'Floor Fan', category: 'hvac', w: 0.7, d: 0.7, h: 1.5, color: '#374151', rule: 'floor' },
  // lighting & AV: for mounted items H = mounting height
  { id: 'highbay', label: 'UFO High-Bay Light (H = mount height)', category: 'tech', w: 0.5, d: 0.5, h: 6.0, color: '#2f3237', rule: 'floor' },
  { id: 'tracklight', label: 'Track Light (H = mount height)', category: 'tech', w: 2.5, d: 0.15, h: 3.2, color: '#2b2f35', rule: 'floor' },
  { id: 'cctv', label: 'CCTV Camera (H = mount height)', category: 'tech', w: 0.3, d: 0.3, h: 3.0, color: '#e8eaec', rule: 'floor' },
  { id: 'speaker', label: 'PA Speaker (H = mount height)', category: 'tech', w: 0.35, d: 0.3, h: 2.8, color: '#23262b', rule: 'floor' },
  // hold-washing room: a lean-to extension against the outside of the building
  { id: 'washroom', label: 'Hold Washing Room (outdoor)', category: 'room', w: 3.0, d: 2.5, h: 2.5, color: '#cfd6dd', rule: 'outdoor' },
  // site & outdoors
  { id: 'tree_small', label: 'Small Tree', category: 'site', w: 1.6, d: 1.6, h: 2.2, color: '#6ca055', rule: 'outdoor' },
  { id: 'tree_big', label: 'Big Tree', category: 'site', w: 4.0, d: 4.0, h: 7.0, color: '#4e7d3e', rule: 'outdoor' },
  { id: 'fence', label: 'Fence', category: 'site', w: 3.0, d: 0.12, h: 1.5, color: '#8a9099', rule: 'outdoor' },
  { id: 'hedge', label: 'Hedge Fence', category: 'site', w: 3.0, d: 0.6, h: 1.3, color: '#4e7d3e', rule: 'outdoor' },
  { id: 'lightpole', label: 'Light Pole', category: 'site', w: 0.5, d: 0.5, h: 4.5, color: '#3f454d', rule: 'outdoor' },
  { id: 'car', label: 'Car (parked)', category: 'site', w: 4.6, d: 1.8, h: 1.5, color: '#5b7fb4', rule: 'outdoor' },
  { id: 'moto', label: 'Motorcycle', category: 'site', w: 2.1, d: 0.8, h: 1.2, color: '#c2452f', rule: 'outdoor' },
  { id: 'carport', label: 'Carport Roof', category: 'site', w: 5.5, d: 5.5, h: 2.7, color: '#9aa3ad', rule: 'outdoor' },
  // garden set
  { id: 'tree_cone', label: 'Conifer Tree', category: 'site', w: 2.2, d: 2.2, h: 4.5, color: '#3f6d3a', rule: 'outdoor' },
  { id: 'tree_slim', label: 'Cypress (columnar)', category: 'site', w: 1.2, d: 1.2, h: 5.0, color: '#4a7a42', rule: 'outdoor' },
  { id: 'pond', label: 'Garden Pond', category: 'site', w: 4.0, d: 3.0, h: 0.35, color: '#4f7d9e', rule: 'outdoor' },
  { id: 'fountain', label: 'Fountain', category: 'site', w: 2.0, d: 2.0, h: 1.8, color: '#b9c0c7', rule: 'outdoor' },
  { id: 'bench_out', label: 'Garden Bench', category: 'site', w: 1.8, d: 0.6, h: 0.9, color: '#8a6f52', rule: 'outdoor' },
  { id: 'table_out', label: 'Outdoor Table Set', category: 'site', w: 1.8, d: 1.8, h: 0.75, color: '#7c828a', rule: 'outdoor' },
  { id: 'path', label: 'Concrete Path', category: 'site', w: 6.0, d: 1.5, h: 0.06, color: '#c9c5bc', rule: 'outdoor' },
  { id: 'awning', label: 'Canvas Awning', category: 'site', w: 4.0, d: 3.0, h: 2.8, color: '#d8cdb8', rule: 'outdoor' },
  { id: 'umbrella', label: 'Patio Umbrella', category: 'site', w: 2.2, d: 2.2, h: 2.4, color: '#b45341', rule: 'outdoor' },
]

export const CATEGORY_LABELS: Record<Category, string> = {
  door: 'Doors',
  parking: 'Parking',
  reception: 'Reception',
  room: 'Rooms',
  fixture: 'Fixtures',
  zone: 'Activity Zones',
  wall_low: 'Boulder Wall',
  wall_high: 'Lead Wall (Tall)',
  wall_island: 'Island Boulder',
  wall_custom: 'Custom Walls',
  mat: 'Landing Mats',
  mezzanine: 'Mezzanine',
  stairs: 'Stairs',
  column: 'Columns',
  partition: 'Partitions',
  furniture: 'Furniture',
  person: 'People',
  ceiling: 'Ceiling',
  hvac: 'Air & Ventilation',
  tech: 'Lighting & AV',
  site: 'Site & Outdoors',
}

// Order in which categories appear in the palette
export const CATEGORY_ORDER: Category[] = [
  'wall_low',
  'wall_high',
  'wall_island',
  'wall_custom',
  'mat',
  'mezzanine',
  'stairs',
  'column',
  'partition',
  'zone',
  'room',
  'reception',
  'fixture',
  'furniture',
  'person',
  'ceiling',
  'hvac',
  'tech',
  'door',
  'parking',
  'site',
]
